增補 滿足 systemctl 執行需求、docker 程式包； 文件 編寫 描述其問題
增補 使 systemctl 以 exit 0 代碼退出
增補 docker 程式包
文件 編寫 systemctl 描述

diff --git a/mizarch/bwaycer/Dockerfile b/mizarch/bwaycer/Dockerfile
--- a/mizarch/bwaycer/Dockerfile
+++ b/mizarch/bwaycer/Dockerfile
@@ -3,6 +3,15 @@ FROM bwaycer/mizarch:base
 MAINTAINER BwayCer (https://github.com/BwayCer/image.docker)
 
 
+# 在非 PID 1 init 進程中調用 systemctl 命令會以 `exit 1` 退出並顯示以下訊息：
+# ```
+# System has not been booted with systemd as init system (PID 1). Can't operate.
+# Failed to connect to bus: Host is down
+# ```
+RUN cp "/bin/systemctl" "/bin/systemctl.real"; \
+    echo "echo In Docker." > "/bin/systemctl"
+
+
 ## 臺北時間
 RUN ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
 
